### ISSUE TITLE
To-do list entrega 1

### ISSUE THREAD

**Issue by Mylena-angelica** [UnBArqDsw2023-2/2023.2_G1_ProjetoAmazon#42]
- [x] Checklist dos documentos que ainda precisam ser feitos
- [x] Checklist dos documentos que necessitam de revisão
- [ ] Todos merges ok
- [ ] Deploy na gitpage
- [x] Documentos de entrega
- [x] Opinião dos membros
- [ ] Pasta zip
- [x] Atualizar cronograma
- [x] Dividir a apresentação

**Comment by Mylena-angelica** [comment]
Documentação para fazer:

- [ ] Rich Picture
- [ ] Diagrama causa-efeito
- [ ] Mkdocs- gitpage
- [ ] Modelagem BPMN
- [ ] Protótipo

**Comment by Mylena-angelica** [comment]
Documentos para revisão:

- [ ] 5W2H
- [ ] Brainstorm
- [ ] StoryBoard
- [ ] Plano de risco
- [ ] 3.0 Documentação final (opiniões e tarefas)
- [ ] PDF de apresentação
- [ ]  Rich Picture
- [ ]  Diagrama causa-efeito
- [ ]  Mkdocs- gitpage 
- [ ]  Modelagem BPMN
- [ ]  Protótipo 
- [ ]  Atualizar cronograma

**Comment by guilherme-puida** [comment]
> Documentação para fazer:
> 
>     * [ ]  Rich Picture

Vou fazer!

**Comment by ananorberto** [comment]
> Documentação para revisar:
> 
>     * [ ]  Brainstorm

Posso revisar esse!

**Comment by eng-Bruno** [comment]
> Documentação para revisar:
> 
>     * [ ]  Rich Picture

Finalizei meu Rich Picture!

**Comment by guilherme-puida** [comment]
Fiz o documento do Rich Picture. Solicito revisão :^)
