### ISSUE TITLE
TO-DO - Todo list: Entrega 2

### ISSUE THREAD

**Issue by ananorberto** [UnBArqDsw2023-2/2023.2_G1_ProjetoAmazon#86]
- [ ]  Checklist dos documentos que ainda precisam ser feitos
- [ ]  Checklist dos documentos que necessitam de revisão
- [ ]  Todos merges ok
- [ ]  Deploy na gitpage
- [ ]  Documentos de entrega
- [ ]  Opinião dos membros
- [ ]  Pasta zip
- [ ]  Atualizar cronograma
- [ ]  Dividir a apresentação

**Comment by ArthurFerreiraRodrigues** [comment]
Issue não utilizad
